name: Actualizador de Precios Dipisa

on:
  schedule:
    # Se ejecuta todos los días a las 08:00, 13:00 y 18:00 (Hora de Chile / 12, 17, 22 UTC)
    - cron: '20 17 * * *'
  workflow_dispatch: # Te agrega un botón en GitHub para correrlo manualmente cuando quieras

jobs:
  scraping:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: |
          pip install pandas pyyaml requests curl_cffi

      - name: Ejecutar Extractor de Precios
        env:
          SCRAPERAPI_KEY: ${{ secrets.SCRAPERAPI_KEY }}
        run: python scraper.py

      - name: Guardar y subir nuevos precios
        run: |
          git config --global user.name "Dipisa-Bot"
          git config --global user.email "bot@dipisa.cl"
          git add datos_procesados.json
          # Si hay cambios en los precios, los sube a GitHub automáticamente
          git diff --quiet && git diff --staged --quiet || (git commit -m "🤖 Actualización automática de precios" && git push)
