[theme]
# Azul corporativo profundo (estilo Dipisa/Ovella)
primaryColor = "#004B87" 

# Fondo de la página gris perla muy limpio
backgroundColor = "#F4F6F9" 

# Fondo de las tarjetas y menú lateral en blanco puro
secondaryBackgroundColor = "#FFFFFF" 

# Texto oscuro elegante
textColor = "#1E293B" 

# Tipografía moderna y sin serifa
font = "sans serif"
