[theme]
# Morado/índigo de la marca Dipisa (del logo real, no un azul genérico)
primaryColor = "#4917A1"

# Fondo de la página gris perla muy limpio
backgroundColor = "#F4F6F9"

# Fondo de las tarjetas y menú lateral en blanco puro
secondaryBackgroundColor = "#FFFFFF"

# Texto oscuro tomado del logo (gris carbón, no negro puro)
textColor = "#1B252C"

# Tipografía moderna y sin serifa
font = "sans serif"
